apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: sparkle-note
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 055679187412.dkr.ecr.ap-south-1.amazonaws.com/sparkle-note-frontend:33e41b7
        ports:
        - containerPort: 80

        envFrom:
          - configMapRef:
              name: frontend-config
