#4. IRSA ServiceAccount for Load Balance Controller
# Annotation with the IAM role ARN 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::055679187412:role/aws-load-balancer-controller-role