apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: sparkle-note
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: backend:1.14.2
        ports:
        - containerPort: 8080

        env:
          - name: PORT
            value: "8080"

          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: sparkle-note-secrets
                key: MONGO_URI
