apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sparkle-note-secrets 
  namespace: sparkle-note
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: sparkle-note-secrets 
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: MONGODB_URI
      remoteRef:
        key: sparkle-note/prod/app-secrets
        property: MONGODB_URI
        
    - secretKey: MONGODB_DB_NAME
      remoteRef:
        key: sparkle-note/prod/app-secrets
        property: MONGODB_DB_NAME

    - secretKey: DATABASE_URL
      remoteRef:
        key: sparkle-note/prod/app-secrets
        property: DATABASE_URL


